import math

max_radius=3
max_radius_squared=max_radius*max_radius

layouts=[]

for rs in range(0,max_radius_squared+1):
    layout=[]
    for z in range(-max_radius,max_radius+1):
        for y in range(-max_radius,max_radius+1):
            for x in range(-max_radius,max_radius+1):
                if x*x + y*y + z*z == rs:
                    layout.append((x, y, z)) 
    if len(layout) > 0:
        duplicate=False
        for (rsl,l) in layouts:
            if (rsl == 0 or (not(duplicate) and rs%rsl==0 and len(l) == len(layout))):
                if rsl == 0:
                    mul=1
                else:
                    mul=math.sqrt(rs//rsl)
                l_scaled=[(x*mul, y*mul, z*mul) for (x, y, z) in l.copy()]
                duplicate=set(layout)==set(l_scaled)
        if not(duplicate):
            layouts.append((rs, layout))

def sec_elem(s):
    return s[1]

layouts=sorted(layouts, key=lambda tup: (len(tup[1]), tup[0]))

with open('output_layouts.h', 'w') as f:
    f.write('// This file was generated by the output_layouts_generator.py PYTHON script\n')
    f.write('#ifndef OUTPUT_LAYOUTS_H\n')
    f.write('#define OUTPUT_LAYOUTS_H\n')
    f.write('\n')
    f.write('#ifdef __cplusplus\n')
    f.write('extern "C" {\n')
    f.write('#endif\n')
    f.write('\n')
    f.write('typedef enum {\n')
    for (rsl,l) in layouts:
        f.write('\tOUTPUT_LAYOUT_N' + str(len(l)) + '_RS' + str(rsl) + ', \n')
    f.write('\tOUTPUT_LAYOUT_COUNT\n')
    f.write('} OUTPUT_LAYOUT_T;\n')
    f.write('\n')
    f.write('\n')
    f.write('const char *output_layout_name(OUTPUT_LAYOUT_T layout);\n')
    f.write('const int *output_layout_offsets(OUTPUT_LAYOUT_T layout, int* count, int* radius_sq);\n')
    f.write('\n')
    f.write('#ifdef __cplusplus\n')
    f.write('}\n')
    f.write('#endif\n')
    f.write('\n')
    f.write('#endif //OUTPUT_LAYOUTS_H\n')

with open('output_layouts.c', 'w') as f:
    f.write('#include "output_layouts.h"\n')
    f.write('#include <stddef.h>\n')
    f.write('\n')
    for (rsl,l) in layouts:
        f.write('static int output_layout_n' + str(len(l)) + '_rs' + str(rsl) + '_offsets[' + str(len(l)*3) + '] = {')
        for (x,y,z) in l:
            f.write(str(x) + ',' + str(y) + ',' + str(z) + ',')
        f.write('};\n')
    f.write('\n')
    f.write('const char *output_layout_name(const OUTPUT_LAYOUT_T layout) {\n')
    f.write('\tswitch (layout) {\n')
    for (rsl,l) in layouts:
        f.write('\t\tcase OUTPUT_LAYOUT_N' + str(len(l)) + '_RS' + str(rsl) + ':\n')
        f.write('\t\t\treturn "' + str(len(l)) + ' receivers, ' + str(rsl) + ' radius sq";\n')
    f.write('\t}\n')
    f.write('\treturn NULL;\n')
    f.write('}\n')
    f.write('\n')
    f.write('const int *output_layout_offsets(const OUTPUT_LAYOUT_T layout, int *count, int* radius_sq) {\n')
    f.write('\tswitch (layout) {\n')
    for (rsl,l) in layouts:
        f.write('\t\tcase OUTPUT_LAYOUT_N' + str(len(l)) + '_RS' + str(rsl) + ':\n')
        f.write('\t\t\t*count = ' + str(len(l)) + ';\n')
        f.write('\t\t\t*radius_sq = ' + str(rsl) + ';\n')
        f.write('\t\t\treturn output_layout_n' + str(len(l)) + '_rs' + str(rsl) + '_offsets;\n')
    f.write('\t}\n')
    f.write('\t*count = 0;\n')
    f.write('\t*radius_sq = 0;\n')
    f.write('\treturn NULL;\n')
    f.write('}\n')
    
import os
import glob

files = glob.glob("plugin/array2sh_presets/*")
for f in files:
    os.remove(f)
    
sample_rates = [16000, 22050, 32000, 44100, 48000]

with open('array2sh_presets/INFO.md', 'w') as f:
    f.write('The following are the appropriate radius values according to the sample rate and layout used:\n\n')
    for fs in sample_rates:
        f.write('#### ' + str(fs) + 'Hz:\n\n')
        for (rsl,l) in layouts:
            if rsl > 0:
                radius=343*math.sqrt(3)/fs*1000*math.sqrt(rsl)
                f.write('* ' + str(len(l)) + ' receivers, ' + str(rsl) + ' radius sq' + ': ' + str(radius) + 'mm\n')
        f.write('\n')
  
for (rsl,l) in layouts:
    if rsl > 0:
        name = str(len(l)) + ' receivers, ' + str(rsl) + ' radius sq'
        with open('array2sh_presets/' + name + '.json', 'w') as f:
            f.write('{\n')
            f.write('\t\"Name\": \"' + name +'\",\n')
            f.write('\t\"Description\": \"Check correct array radius in INFO.md depending on sample rate\",\n')
            f.write('\t\"GenericLayout\": {\n')
            f.write('\t\t\"Name\": \"Sensor Directions\",\n')
            f.write('\t\t\"Elements\": [\n')
            channel=1
            comma=False
            for (x,y,z) in l:
                azi = -math.atan2(x, z) / math.pi * 180
                el = math.atan2(y, math.sqrt(x * x + z * z)) / math.pi * 180
                if comma:
                     f.write(',')
                f.write('\t\t\t{\n')
                f.write('\t\t\t\t\"Azimuth\": ' + str(azi) + ',\n')
                f.write('\t\t\t\t\"Elevation\": ' + str(el) + ',\n')
                f.write('\t\t\t\t\"Radius\": 1.0,\n')
                f.write('\t\t\t\t\"IsImaginary\": false,\n')
                f.write('\t\t\t\t\"Channel\": ' + str(channel) + ',\n')
                f.write('\t\t\t\t\"Gain\": 1.0\n')
                f.write('\t\t\t}\n')
                comma=True
                channel=channel+1
            f.write('\t\t]\n')
            f.write('\t}\n')
            f.write('}\n')

