// This file was generated by the output_layouts_generator.py PYTHON script
#ifndef OUTPUT_LAYOUTS_H
#define OUTPUT_LAYOUTS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	OUTPUT_LAYOUT_N1_RS0, 
	OUTPUT_LAYOUT_N6_RS1, 
	OUTPUT_LAYOUT_N8_RS3, 
	OUTPUT_LAYOUT_N12_RS2, 
	OUTPUT_LAYOUT_N24_RS5, 
	OUTPUT_LAYOUT_N24_RS6, 
	OUTPUT_LAYOUT_N30_RS9, 
	OUTPUT_LAYOUT_COUNT
} OUTPUT_LAYOUT_T;


const char *output_layout_name(OUTPUT_LAYOUT_T layout);
const int *output_layout_offsets(OUTPUT_LAYOUT_T layout, int* count, int* radius_sq);

#ifdef __cplusplus
}
#endif

#endif //OUTPUT_LAYOUTS_H
