% Build the IIR coeficients using the Yule-Walker method
function [b,a] = fit_IIR_R(fs, freqs, alpha, order, plot_original, plot_fit)
    freqs = [0, freqs];
    freqs = [freqs, fs/2];
    norm_freqs = freqs/fs*2;
    alpha = [alpha, alpha(length(alpha))];
    alpha = [alpha(1), alpha];
    R = sqrt(1.0 - alpha);
    [b,a] = yulewalk(order,norm_freqs,R);
    b(isnan(b))=0; % Fix absorber material fit
    if (plot_original)
        plot(freqs,R,'-o', 'DisplayName','Reference')
    end
    if (plot_fit)
        [h,w] = freqz(b,a,1024);
        plot(w/pi*fs/2,abs(h), 'DisplayName',num2str(order))
    end
    if not(isstable(b,a))
        error("Unstable filter found!");
    end
end

% Coefficients taken from
% Oxnard, Stephen, et al. "Frequency-Dependent Absorbing Boundary Implementations in 3D Finite Difference Time Domain Room Acoustics Simulations." Proceedings of EURONOISE, Maastricht, The Netherlands (2015).
materials_freqs = [63 125 250 500 1000 2000 4000];
materials_names = [
    "ABSORBER";
    "PLASTER";
    "WOOD";
    "CONCRETE"
];
materials_alpha = [
    [1.00 1.00 1.00 1.00 1.00 1.00 1.00]; % absorber
    [0.08 0.08 0.20 0.50 0.40 0.40 0.36]; % plaster
    [0.15 0.15 0.11 0.10 0.07 0.06 0.06]; % wood
    [0.02 0.02 0.03 0.03 0.03 0.04 0.07]  % concrete
];
materials_count = 4;
% Common sample rates
fs_s = [16000, 22050, 32000, 44100, 48000];
% Filter orders
IIR_orders = [1,2,4,6,8];

% Header file
fid = fopen('../include/dwr3/gen/boundary_filters.h','wt');
fprintf(fid, '// This file was generated by the boundary_filters_generator.m MATLAB script\n');
fprintf(fid, '#ifndef DWR3_BOUNDARY_FILTERS_H\n');
fprintf(fid, '#define DWR3_BOUNDARY_FILTERS_H\n\n');
fprintf(fid, '#ifdef __cplusplus\n');
fprintf(fid, 'extern "C" {\n');
fprintf(fid, '#endif\n\n');
fprintf(fid, 'typedef enum {\n');
for material_name = materials_names
    fprintf(fid, '\tDWR3_BOUNDARY_FILTER_MATERIAL_%s,\n', material_name);
end
fprintf(fid, '\tDWR3_BOUNDARY_FILTER_MATERIAL_COUNT,\n');
fprintf(fid, '} DWR3_BOUNDARY_FILTER_MATERIAL_T;\n\n');
fprintf(fid, 'const char *dwr3_boundary_filter_name(DWR3_BOUNDARY_FILTER_MATERIAL_T material);\n\n');
fprintf(fid, 'const dwr3_boundary_filter_t *dwr3_boundary_filter_material(DWR3_BOUNDARY_FILTER_MATERIAL_T material, int sample_rate);\n\n');
fprintf(fid, '#ifdef __cplusplus\n');
fprintf(fid, '}\n');
fprintf(fid, '#endif\n\n');
fprintf(fid, '#endif //DWR3_BOUNDARY_FILTERS_H\n');
fclose(fid);

% Source file
fid = fopen('../src/gen/boundary_filters.c','wt');
fprintf(fid, '// This file was generated by the boundary_filters_generator.m MATLAB script\n');
fprintf(fid, '#include <stddef.h>\n');
fprintf(fid, '#include <dwr3/dwr3.h>\n\n');
for order = IIR_orders
    fprintf(fid, '#if (DWR3_BOUNDARY_FILTER_ORDER) == %d\n', order);
    for i = 1:materials_count
        for fs = fs_s
            fprintf(fid, 'static const dwr3_boundary_filter_t DWR3_BOUNDARY_FILTER_MATERIAL_%s_%i = {', materials_names(i), fs);
            [b,a] = fit_IIR_R(fs, materials_freqs, materials_alpha(i,:), order, false, false);
            fprintf(fid, "{%s},{%s}", strip(sprintf("%.16f,", b), ","), strip(sprintf("%.16f,", a), ","));
            fprintf(fid, '};\n');
        end
    end
    fprintf(fid, '#endif\n\n');
end
fprintf(fid, 'const char *dwr3_boundary_filter_name(const DWR3_BOUNDARY_FILTER_MATERIAL_T material) {\n');
fprintf(fid, '\tswitch (material) {\n');
for i = 1:materials_count
    fprintf(fid, '\t\tcase DWR3_BOUNDARY_FILTER_MATERIAL_%s: return "%s";\n', materials_names(i), regexprep(lower(materials_names(i)),'^.', '${upper($0)}'));
end
fprintf(fid, '\t\tdefault: break;\n');
fprintf(fid, '\t}\n');
fprintf(fid, '\treturn NULL;\n');
fprintf(fid, '}\n');
fprintf(fid, 'const dwr3_boundary_filter_t *dwr3_boundary_filter_material(const DWR3_BOUNDARY_FILTER_MATERIAL_T material, const int sample_rate) {\n');
fprintf(fid, '\tswitch (material) {\n');
for i = 1:materials_count
    fprintf(fid, '\t\tcase DWR3_BOUNDARY_FILTER_MATERIAL_%s: switch (sample_rate) {\n', materials_names(i));
    for fs = fs_s
       fprintf(fid, '\t\t\tcase %i: return &DWR3_BOUNDARY_FILTER_MATERIAL_%s_%i;\n', fs, materials_names(i), fs);
    end
    fprintf(fid, '\t\t\tdefault: break;\n');
    fprintf(fid, '\t\t} break;\n');
end
fprintf(fid, '\t\tdefault: break;\n');
fprintf(fid, '\t}\n');
fprintf(fid, '\treturn NULL;\n');
fprintf(fid, '}\n');
fclose(fid);

% Diagnostic plots
for fs = fs_s
    for i = 1:materials_count
        figure
        hold on
        for order = IIR_orders
            fit_IIR_R(fs, materials_freqs, materials_alpha(i,:), order, order == 1, true);
        end
        xlabel('Hz')
        ylabel('Magnitude')
        grid
        legend();
        hold off
    end
end